### ISSUE TITLE
Add pHat/wHat discovery

### ISSUE THREAD

**Issue by danieldulaney** [wezm/ssd1675#18]
In addition to the SPI interface, the Inky pHat and wHat boards also implement a mostly-undocumented I2C interface that allows the contents of the EEPROM to be dumped, which allows the boards to be identified (resolution, available colors, board revision, etc.). This is how the Inky Python library does board detection.

I have some working Rust code that uses the embedded_hal I2C interfaces to do autodetection. Would there be interest in a PR adding those capabilities to this crate? I know it's slightly outside the SSD1675 chip in particular, but it doesn't require any new dependencies and would better support Inky [pw]Hat users.

If not, I'll most likely post a new crate with just that detection subsystem.

**Comment by wezm** [comment]
That sounds useful in principle. I would ideally like to split out the Inky specific parts into a separate crate so that there can be a core ssd167x crate that is not Inky specific. It's been on my todo list for a long time but I've still not got around to it. I still hope to get there eventually. Maybe the best option for now is for you to publish a separate crate. I'd be open to giving it a mention in the README of this one.

**Comment by danieldulaney** [comment]
Makes sense! I'll shift discussion over to #19.
